version: '3'

services:
  ksqldb-server:
    image: confluentinc/cp-ksqldb-server:7.2.0
    hostname: ksqldb-server1
    container_name: ksqldb-server1
    ports:
      - "8087:8088"
    environment:
      KSQL_LISTENERS: http://0.0.0.0:8088
      KSQL_BOOTSTRAP_SERVERS: kafka1:9092,kafka2:9092,kafka3:9092
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
      KSQL_KSQL_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      KSQL_KSQL_CONNECT_URL: "http://kafka-connect:8083"
      KSQL_KSQL_SERVICE_ID: 1

networks:
  default:
    name: k_cluster_net
    external: true